const Menu = [
  {
    id: "1",
    image: "../images/maggi.jpg",
    name: "Maggi",
    category: "Breakfast",
    price: "12₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },

  {
    id: "2",
    image: "../images/pakoda.jpg",
    name: "Pakoda",
    category: "Evening",
    price: "20₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },
  {
    id: "3",
    image: "../images/puri.jpg",
    name: "Puri",
    category: "Breakfast",
    price: "10₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },
  {
    id: "4",
    image: "../images/chola.jpg",
    name: "Chola-Bhatura",
    category: "Lunch",
    price: "50₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },
  {
    id: "5",
    image: "../images/pizza.jpg",
    name: "Pizza",
    category: "Evening",
    price: "80₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },
  {
    id: "6",
    image: "../images/nonvegthali.jpg",
    name: "Thali",
    category: "Dinner",
    price: "180₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },
  {
    id: '7',
    image: "../images/sweet.jpg",
    name: "Sweets",
    category: "Dinner",
    price: "60₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },
  {
    id: "8",
    image: "../images/rajmarice.jpg",
    name: "Rajma-Rice",
    category: "Lunch",
    price: "60₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },
  {
    id: "9",
    image: "../images/samosa.jpg",
    name: "Samosa",
    category: "Evening",
    price: "10₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis similique maxime voluptates neque illum? Veniam nemo, consequatur ducimus et quisquam architecto. Mollitia reprehenderit",
  },
  {
    "id": "10",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/79619/joes-kc-ribs-brisket-and-burnt-ends.6710e994980e485e6441b794717ad6fb.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Brisket & Burnt Ends",
    "price": "30₹",
    category: "Evening",
    "description": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla omnis incidunt illo impedit doloremque corporis.cing elit. Nulla omnis incidunt illo impedit doloremque corporis."
  },
  {
    "id": "11",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/66752/carolina-bbq-oink-sampler.1340b5a10cedc238cb2280306dd1d5a5.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Kings BBQ",
    "description": "Carolina BBQ Oink Sampler",
    "price": 89,
    category: "Lunch",
    "rate": 4,
  },
  {
    "id": "12",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131249/texas-monthlys-1-bbq-brisket.1006a061be7acae03992e420fbca995a.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Snow's BBQ",
    "description": "Texas Monthly's #1 BBQ Brisket",
    "price": 199,
    category: "Evening",
    "rate": 5,
  },
  {
    "id": "13",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/137366/Central-BBQ-Ribs-Pulled-Pork-Dinner-1.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Central BBQ",
    "description": "Ribs & Pulled Pork Dinner for 4",
    "price": 79,
    category: "Lunch",
    "rate": 5,
  },
  {
    "id": "14",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110384/whole-brisket-texas-barbecue-bbq-sauce.e07ee4818b20ed43d217bf67fedd41ce.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Arthur Bryant's Barbeque",
    "description": "Barbeque Sampler for 8",
    "price": 139,
    category: "Evening",
    "rate": 5,
  },
  {
    "id": "15",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110384/whole-brisket-texas-barbecue-bbq-sauce.e07ee4818b20ed43d217bf67fedd41ce.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Franklin Barbecue",
    "description": "Whole Brisket + Texas Barbecue BBQ Sauce",
    "price": 249,
    category: "Lunch",
    "rate": 5,
  },
        
  {
    "id": "16",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/101071/whole-texas-smoked-brisket.a5558a25381e271408e197936e7985d8.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Terry Black's Barbecue",
    "description": "Whole Texas Smoked Brisket",
    "price": 189,
    category: "Lunch",
    "rate": 4,
  },
  {
    "id": "17",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/137368/Central-BBQ-Ribs-Pulled-Pork-Party-Pack-1_.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Central BBQ",
    "description": "Ribs & Pulled Pork Dinner for 8",
    "price": 109,
    category: "Evening",
    "rate": 5,
  },
  {
    "id": "18",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133378/choose-your-own-world-championship-bbq-4-pack.d5216e2b1c2a92f481fc9d1c7a15e8df.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Big Bob Gibson Bar-B-Q",
    category: "Lunch",
    "description": "Choose Your Own World Championship BBQ - 4 Pack",
    "price": 109.95,
    "rate": 4,
  },
  {
    "id": "19",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/91821/best-of-texas-bbq-combo-serves-14.7ae90266335e539c67e77fed14b43029.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Snow's BBQ",
    "description": "Best of Texas BBQ Combo - Serves 14",
    "price": 269,
    category: "Evening",
    "rate": 4,
  },
  {
    "id": "20",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134182/mighty-quinns-bbq-sampler-pack.1bfe4a0665edc565756f5241bf25840e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Mighty Quinn's BBQ",
    category: "Lunch",
    "description": "Mighty Quinn's BBQ Sampler Pack",
    "price": 169,
    "rate": 5,
  },
  {
    "id": "21",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132122/the-big-ugly-bbq-dinner-for-6.2dfae7818811adddce85cc1a910881a0.jpeg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Ugly Drum",
    category: "Lunch",
    "description": "The Big Ugly BBQ Dinner for 6",
    "price": 229,
    "rate": 4,
  },
  {
    "id": "22",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/92395/post-oak-smoked-usda-prime-half-brisket.6f17178dde7d806670bcc73ff11762b3.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Southside Market & Barbeque",
    "description": "Post Oak Smoked USDA Prime Half Brisket",
    "price": 109,
    category: "Evening",
    "rate": 4,
  },
      {
    "id": "23",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/96242/bbq-ribs-and-pulled-pork-dinner-for-6.ba9ea2ed663fc67effa9fd7a85624625.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    category: "Breakfast",
    "name": "The Shed BBQ & Blues Joint",
    "description": "BBQ Ribs & Pulled Pork Dinner for 6",
    "price": 109,
    "rate": 5,
  },
  {
    "id": "24",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131846/whole-brisket-sausage-texas-barbecue-bbq-sauce.ffb470cab2f454fd848faa5dddfe65f5.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    category: "Breakfast",
    "name": "Franklin Barbecue",
    "description": "Whole Brisket + Sausage + Texas Barbecue BBQ Sauce",
    "price": 289,
    "rate": 5,
      }    ,
  {
    "id": "25",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/108725/hong-kong-boba-tea-kit-for-6.63841de36d8e5edfafa13023fc303285.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "New Territories",
    "description": "Hong Kong Boba Tea Kit for 6",
    "price": 59,
    category: "Evening",
    "rate": 4,
  },
  {
    "id": "26",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/126836/guys-caliente-margaritas-for-12.ca8c6bc06b8f1039549385ffcebc749d.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Guy Fieri",
    category: "Breakfast",
    "description": "Guy's Caliente Margaritas for 12",
    "price": 69,
    "rate": 5,
  },
  {
    "id": "27",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134036/woodford-reserve-mint-julep-syrup.ef523ac7cbae5f4aba6b058207f490d2.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Woodford Reserve",
    "description": "Woodford Reserve Mint Julep Syrup",
    "price": 39,
    category: "Evening",
    "rate": 4,
  },
  {
    "id": "28",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/84522/new-orleans-hurricane-mix.4613584fc65cb0787024dd24d2a8f4b3.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Franco's Hurricane Mix",
    "description": "New Orleans Hurricane Mix",
    category: "Breakfast",
    "price": 39,
    "rate": 5,
  },
  {
    "id": "29",
    "image": "https://goldbelly.imgix.net/uploads/product_image/image/42820/evan-williams-gourmet-mint-julep-mix-2-pack.a0bd561099dd14bfb33e3363c1c025d0.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Evan Williams",
    category: "Breakfast",
    "description": "Evan Williams Gourmet Mint Julep Mix - 2 Pack",
    "price": 39,
    "rate": 4,
  },
  {
    "id": "30",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132643/margarita-mix.bd48a000d589d3147b14790af3c33fcd.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Johnny Sanchez",
    "description": "Margarita Mix",
    category: "Breakfast",
    "price": 59,
    
    "rate": 5,
  },
  {
    "id": "31",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133235/woodford-reserve-mint-julep-syrup-2-pack.0ac76063f151988113cbaabd0eaa829f.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Woodford Reserve",
    category: "Breakfast",
    "description": "Woodford Reserve Mint Julep Syrup - 2 Pack",
    "price": 59,
    "rate": 5,
  },
  {
    "id": "32",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/92899/evan-williams-gourmet-mint-julep-mix.c90e8c3ed5ac0dc1c85139e6b7b8521c.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Evan Williams",
    category: "Breakfast",
    "description": "Evan Williams Gourmet Mint Julep Mix",
    "price": 25,
    "rate": 5,
  },
  {
    "id": "33",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132264/knock-you-naked-strawberry-margarita-mix.c51ce9329ab84709e5b1d3d474cbb7e2.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Fat Mama's Tamales",
    
    "description": "\"Knock-You-Naked\" Strawberry Margarita Mix",
    "price": 39,
    category: "Evening",
    "rate": 4,
  },
  {
    "id": "34",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110906/bo-ssam-dinner-for-4.c4a32e8801e2f0283e0565bbe8493149.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Grady's Cold Brew",
    category: "Breakfast",
    "description": "Cold Brew Concentrate Variety - 6 Pack",
    "price": 60,
    "rate": 5,
  },
  {
    "id": "35",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134437/organic-shots-bundle-12-pack.73d62cee42bd9a0c561331b2806e3ac0.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    category: "Breakfast",
    "name": "Juice Press",
    "description": "Organic Shots Bundle-12 Pack",
    "price": 69,
    "rate": 4,
  },
  {
    "id": "36",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132258/papaya-king-tropical-drink.206f7c5b09ed7affb414f9bc7fe32447.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Papaya King",
    "description": "Papaya King - Tropical Drink",
    "price": 69,
    category: "Evening",
    "rate": 4,
  },
  {
    "id": "37",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110906/bo-ssam-dinner-for-4.c4a32e8801e2f0283e0565bbe8493149.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Momofuku",
    category: "Breakfast",
    "description": "Half Bo Ssäm Dinner for 4-6",
    "price": 169,
    "rate": 4,
  },
  {
    "id": "38",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133100/legendary-seafood-gumbo.a4010efb8ba0569ff59d68c3723f0963.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Commander's Palace",
    "description": "Legendary Seafood Gumbo",
    "price": 89,
    "rate": 4,
    category: "Evening",
  },
  {
    "id": "39",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/137148/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Gramercy Tavern",
    category: "Dinner",
    "description": "The Gramercy Tavern Burger - 4 Pack",
    "price": 99,
    "rate": 4,
  },
  {
    "id": "40",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134235/complete-fried-chicken-dinner-for-4.aeabf841c124b9cc2fb0166f27790999.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Blue Ribbon",
    category: "Dinner",
    "description": "\"The Coop\" Complete Fried Chicken Dinner for 4",
    "price": 119,
    "rate": 4,
  },
  {
    "id": "41",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132987/traditional-meat-empanadas-with-llajua-sauce-12-pack.f2adcfeb4ccf027675047f1367ce83ca.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Chef Francis Mallmann",
    category: "Dinner",
    "description": "Traditional Beef Empanadas with Llajua Sauce - 12 Pack",
    "price": 99,
    "rate": 4,
   
        
  },
  {
    "id": "42",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110984/pork-buns-12-pack.67a379b014b23c7fd944ab48b9e720f6.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Momofuku",
    "description": "Pork Buns - 12 Pack",
    category: "Dinner",
    "price": 119,
    "rate": 4,
  },
  {
    "id": "43",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131336/marcus-hot-honey-chicken-and-cornbread-waffles-kit-for-4.618df9b9613b506f65c8342ab2e28b32.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Marcus Samuelsson's Streetbird",
    "description": "Marcus’ Hot Honey Chicken & Cornbread Waffles Kit for 4",
    "price": 99,
    category: "Dinner",
    "rate": 5,
  },
  {
    "id": "44",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/114579/zahav-hummus-and-salatim-spread-for-6-8.137df09ea04ec063480f58ead8fe4b83.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Zahav",
    "description": "Zahav Hummus & Salatim Spread",
    "price": 99,
    "rate": 4,
    category: "Evening",
  },
  {
    "id": "45",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/106027/wood-fired-pizzas-best-seller-4-pack.1653bb05922ba153ac178f8365d27f6d.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Pizzeria Bianco",
    category: "Dinner",
    "description": "Wood Fired Pizzas Best Seller - 4 Pack",
    "price": 129,
    "rate": 5,
  },
  {
    "id": "46",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134704/gramercy-tavern-mushroom-lasagna-4-pack.88c671dec184d8bee908d6f5d8d860f9.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Gramercy Tavern",
    category: "Dinner",
    "description": "Gramercy Tavern Mushroom Lasagna for 4",
    "price": 99,
    "rate": 4,
  },
  {
    "id": "47",
    category: "Evening",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133343/brown-butter-lobster-roll-kit-4-pack.f97b1254243c8628ad1a5cd41227f5d7.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Eventide Oyster Co.",
    "description": "Brown Butter Lobster Roll Kit - 4 Pack",
    "price": 99,
    "rate": 5,
  },
  {
    "id": "48",
    category: "Dinner",
    "image": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/104768/commanders-palace-three-course-shrimp-and-grits-dinner-for-2.984253533e589547e834420efccc174a.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Commander's Palace",
    "description": "Commander's Palace Three-Course Shrimp & Grits Dinner for 2",
    "price": 169,
    "rate": 4,
  },
]
export default Menu;